### ISSUE TITLE
How can i use the library?

### ISSUE THREAD

**Issue by shibenli** [geftimov/android-id-card-reader#2]
the ndk build by gradle or ant?
can you give me the detaile guide？

**Comment by shibenli** [comment]
![qq 20160601134450](https://cloud.githubusercontent.com/assets/7353956/15699399/2c8e19ae-27ff-11e6-9c57-5594b8cd9d20.png)
It give the error when i run the sample

**Comment by geftimov** [comment]
Yes I know,
This library is so huge that I do not have time for.
I will tag it as deprecated.
And have some wrong integration with the tessaract.

Please don't use.
